### ISSUE TITLE
DG Review week 10

### ISSUE THREAD

**Issue by AdarshChugani** [AY1920S2-CS2103T-W17-3/main#202]
Tagging @Okkhoy

Overall good job with the Developer Guide, but we encountered a few issues.

1. Section 3.1.2 "SetTrip Command Execution PlaceHolder" is not displayed. I think you may have forgotten to upload the image?

2. Section 3.2.3 hyperlink states Figurex.x which is a broken link. I think the link provided is incorrect.

3. Section 3.4.3 `Design Consideration` is empty

**Comment by LiuChao93** [comment]
Overall, my group thinks that your group has done a good job for the dg.

Here is a few suggestions that my group has thought of:
1) add more interactions between different key holders
2) a few sequence diagrams are quite similar with each other, reflecting similar operations. Hence it is repetitive.
3) we suggest the sequence diagram figure 11 to bring to the infant, this would give users an overview when they just open this document.
